In [6]:
#intent classification is process of classifying customer's intent by analyzing the language they use
#it is the central aspect of chatbot conversation
#2 phases:training phrase and preset response
#methods for intent classification:
#BoW
#TF-IDF
#CNN with Glove
#BERT

In [7]:
from imblearn.over_sampling import SMOTE

In [8]:
# #!pip install datasets
# from datasets import load_dataset

In [9]:
import pandas as pd
dataset=pd.read_csv("C://Users//user//Downloads//banking77.csv")
dataset

text  label  \
0                         I am still waiting on my card?     11   
1      What can I do if my card still hasn't arrived ...     11   
2      I have been waiting over a week. Is the card s...     11   
3      Can I track my card while it is in the process...     11   
4      How do I know if I will get my card, or if it ...     11   
...                                                  ...    ...   
9998              You provide support in what countries?     24   
9999                  What countries are you supporting?     24   
10000                What countries are getting support?     24   
10001                     Are cards available in the EU?     24   
10002                   Which countries are represented?     24   

            label_text  
0         card_arrival  
1         card_arrival  
2         card_arrival  
3         card_arrival  
4         card_arrival  
...                ...  
9998   country_support  
9999   country_support  
10000  country_support  
10001  country_support  
10002  country_support  

[10003 rows x 3 columns]

In [10]:
# dataset=load_dataset("banking77")

In [11]:
example=dataset["text"]
example

0                           I am still waiting on my card?
1        What can I do if my card still hasn't arrived ...
2        I have been waiting over a week. Is the card s...
3        Can I track my card while it is in the process...
4        How do I know if I will get my card, or if it ...
                               ...                        
9998                You provide support in what countries?
9999                    What countries are you supporting?
10000                  What countries are getting support?
10001                       Are cards available in the EU?
10002                     Which countries are represented?
Name: text, Length: 10003, dtype: object

In [12]:
from transformers import BertTokenizer,BertForSequenceClassification
import torch

In [14]:
labels=dataset['label']
labels

0        11
1        11
2        11
3        11
4        11
         ..
9998     24
9999     24
10000    24
10001    24
10002    24
Name: label, Length: 10003, dtype: int64

In [15]:
dataset['label'].value_counts()

15    187
28    182
6     181
75    180
19    177
     ... 
41     82
18     61
10     59
72     41
23     35
Name: label, Length: 77, dtype: int64

In [16]:
X=dataset['text']
X

0                           I am still waiting on my card?
1        What can I do if my card still hasn't arrived ...
2        I have been waiting over a week. Is the card s...
3        Can I track my card while it is in the process...
4        How do I know if I will get my card, or if it ...
                               ...                        
9998                You provide support in what countries?
9999                    What countries are you supporting?
10000                  What countries are getting support?
10001                       Are cards available in the EU?
10002                     Which countries are represented?
Name: text, Length: 10003, dtype: object

In [17]:
y=dataset['label']
y

0        11
1        11
2        11
3        11
4        11
         ..
9998     24
9999     24
10000    24
10001    24
10002    24
Name: label, Length: 10003, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=dataset['label'])

In [45]:
y_train.value_counts()

15    149
6     145
28    145
75    144
19    141
     ... 
41     66
18     49
10     47
72     33
23     28
Name: label, Length: 77, dtype: int64

In [20]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [21]:
#!pip install --user tensorflow-text

In [23]:
#bert_preprocess=hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3') #preprocess url
#bert_encoder=hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4') #main encoder
bert_encoder=hub.KerasLayer('https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/2')

In [24]:
# model_name = "bert-base-uncased"
# tokenizer = BertTokenizer.from_pretrained(model_name)
# model = BertForSequenceClassification.from_pretrained(model_name)

In [25]:
# def get_sentence_embedding(sentences):
#     preprocessed_text=bert_preprocess(sentences)
#     print(preprocessed_text)
#     return bert_encoder(preprocessed_text)['pooled_output']

In [26]:
#get_sentence_embedding(["Hi"])

{'input_mask': <tf.Tensor: shape=(1, 128), dtype=int32, numpy=
array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>, 'input_word_ids': <tf.Tensor: shape=(1, 128), dtype=int32, numpy=
array([[ 101, 7632,  102,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[-9.99999642e-01,  9.16618928e-02, -9.99756515e-01,
        -3.98032129e-01, -9.97363210e-01,  1.35001808e-01,
        -7.08237112e-01, -8.58935714e-01,  8.86702165e-02,
        -1.03364028e-01,  1.70197785e-01, -9.08058360e-02,
        -1.11357726e-01,  1.00000000e+00, -1.64194643e-01,
        -9.50313449e-01,  9.03155446e-01, -2.76193535e-03,
        -8.38348091e-01,  6.58598617e-02,  9.65345860e-01,
         1.25272483e-01,  4.81814653e-01, -2.58078843e-01,
        -9.99824822e-01, -1.68834291e-02, -9.99732792e-01,
         8.81765783e-01,  9.90791678e-01,  8.16147253e-02,
        -1.08431064e-01,  8.88566375e-02, -9.87177968e-01,
        -5.65082550e-01,  8.60359490e-01,  9.99586582e-01,
        -9.93267238e-01, -1.43460050e-01,  9.81417000e-01,
        -9.97229636e-01,  9.94231045e-01,  9.81468081e-01,
        -9.98334289e-01,  9.59671199e-01, -9.99441862e-01,
        -2.23157823e-01, -9.85262632e-01,  9.98711467e-01,
      

In [27]:
# while True:
#     text = input()
#     if text.lower() == "exit":
#             break
# # Classify the sentiment
#     output = classifier(text)
#     print("Predicted output:",output)


In [28]:
 #for downgrading error came  
#!pip uninstall protobuf

In [29]:
#!pip install protobuf==3.19.0

In [30]:
# model_name = "bert-base-uncased"
# tokenizer = BertTokenizer.from_pretrained(model_name)
# model = BertForSequenceClassification.from_pretrained(model_name, num_labels=len(labels))

In [31]:
# def classifier(text):
#     # Load pre-trained BERT model and tokenizer
#     model_name = "bert-large-uncased"
#     tokenizer = BertTokenizer.from_pretrained(model_name)
#     model = BertForSequenceClassification.from_pretrained(model_name, num_labels=len(labels))dd

#     # Tokenize and encode the input
#     inputs = tokenizer.encode_plus(text, add_special_tokens=True,padding=True, return_tensors="pt")
#     print(inputs)
#     # Get predictions
#     logits = model(**inputs).logits
#     print(logits)
#     # Get predicted label 
#     predicted_label = labels[torch.argmax(logits).item()]

#     return predicted_label

In [32]:
# text = input()
# # Classify the sentiment
# output = classifier(text)
# print("Predicted output:",output)

In [33]:
#bert layers
text_input=tf.keras.layers.Input(shape=(),dtype=tf.string,name="text")
preprocessed_text=bert_preprocess(text_input)
outputs=bert_encoder(preprocessed_text)
#neural network layers
# l=tf.keras.layers.Dropout(0.1,name='dropout')(outputs['pooled_output']) #batch size 768
l=tf.keras.layers.Dense(1,activation='softmax',name='output')(outputs['pooled_output'])
#construct final model
model=tf.keras.Model(inputs=[text_input],outputs=[l])

In [34]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 text (InputLayer)              [(None,)]            0           []                               
                                                                                                  
 keras_layer (KerasLayer)       {'input_mask': (Non  0           ['text[0][0]']                   
                                e, 128),                                                          
                                 'input_word_ids':                                                
                                (None, 128),                                                      
                                 'input_type_ids':                                                
                                (None, 128)}                                                  

In [35]:
METRICS=[tf.keras.metrics.CategoricalAccuracy(name='accuracy'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall')]

In [36]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.002),loss='categorical_crossentropy',metrics=METRICS)

In [37]:
model.fit(X_train,y_train,epochs=5)

Epoch 1/5
251/251 [==============================] - 42s 154ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - precision: 0.9841 - recall: 1.0000
Epoch 2/5
251/251 [==============================] - 36s 145ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - precision: 0.9841 - recall: 1.0000
Epoch 3/5
251/251 [==============================] - 41s 163ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - precision: 0.9841 - recall: 1.0000
Epoch 4/5
251/251 [==============================] - 44s 175ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - precision: 0.9841 - recall: 1.0000
Epoch 5/5
251/251 [==============================] - 41s 163ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - precision: 0.9841 - recall: 1.0000


In [38]:
model.evaluate(X_test,y_test)

63/63 [==============================] - 10s 153ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - precision: 0.9840 - recall: 1.0000


[0.0, 1.0, 0.9840080142021179, 1.0]

In [39]:
y_pred=model.predict(X_test).flatten()
y_pred

63/63 [==============================] - 9s 134ms/step


array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [ ]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
acc

In [ ]:
# y_pred=model.predict(["my name is abhijith"]).flatten()
# y_pred

In [ ]:
#!pip install nlpcloud

In [ ]:
# from getpass import getpass

# NLPCLOUD_API_KEY = getpass()

In [ ]:
# import os
# os.environ["NLPCLOUD_API_KEY"] = NLPCLOUD_API_KEY

In [ ]:
# from langchain.llms import NLPCloud
# from langchain import LLMChain
# from langchain.prompts import PromptTemplate

In [ ]:
 #!pip install typing-extensions --upgrade