In [1]:
#intent classification is process of classifying customer's intent by analyzing the language they use
#it is the central aspect of chatbot conversation
#2 phases:training phrase and preset response
#methods for intent classification:
#BoW
#TF-IDF
#CNN with Glove
#BERT

In [2]:
import os
from apikey import apikey
os.environ['HUGGINGFACEHUB_API_TOKEN']=apikey

In [3]:
import pandas as pd
dataset=pd.read_csv("C://Users//user//Downloads//banking77.csv")
dataset

text  label  \
0                         I am still waiting on my card?     11   
1      What can I do if my card still hasn't arrived ...     11   
2      I have been waiting over a week. Is the card s...     11   
3      Can I track my card while it is in the process...     11   
4      How do I know if I will get my card, or if it ...     11   
...                                                  ...    ...   
9998              You provide support in what countries?     24   
9999                  What countries are you supporting?     24   
10000                What countries are getting support?     24   
10001                     Are cards available in the EU?     24   
10002                   Which countries are represented?     24   

            label_text  
0         card_arrival  
1         card_arrival  
2         card_arrival  
3         card_arrival  
4         card_arrival  
...                ...  
9998   country_support  
9999   country_support  
10000  country_support  
10001  country_support  
10002  country_support  

[10003 rows x 3 columns]

In [4]:
dataset['text'][0]

'I am still waiting on my card?'

In [5]:
len(dataset)

10003

In [6]:
from transformers import BertTokenizer,BertForSequenceClassification
import torch

In [7]:
labels=dataset['label'].unique()
labels

array([11, 13, 32, 17, 34, 46, 36, 12,  4, 14, 33, 41,  1, 49, 23, 56, 47,
        8, 60, 75, 15, 66, 54, 40, 10, 61,  6, 16, 30, 74, 68, 38, 73, 62,
       29, 22,  3, 28, 44, 26, 45, 42, 52, 27, 51, 25, 48, 55, 18, 63, 70,
       67, 53, 21,  7, 64, 50, 35, 65, 71, 39, 58, 43, 72, 76, 37, 59,  5,
       20, 31, 57,  0, 19,  9,  2, 69, 24], dtype=int64)

In [8]:
len(labels)

77

In [9]:
def classifier(text):
    # Load pre-trained BERT model and tokenizer
    model_name = "bert-large-uncased"
    tokenizer = BertTokenizer.from_pretrained(model_name)
    model = BertForSequenceClassification.from_pretrained(model_name, num_labels=len(labels))

    # Tokenize and encode the input
    inputs = tokenizer.encode_plus(text, add_special_tokens=True,padding=True, return_tensors="pt")
    print(inputs)
    # Get predictions
    logits = model(**inputs).logits
    print(logits)
    # Get predicted label 
    predicted_label = labels[torch.argmax(logits).item()]

    return predicted_label

In [10]:
from langchain import HuggingFaceHub,LLMChain
from langchain.prompts import PromptTemplate

In [11]:
from transformers import pipeline
classifier1 = pipeline("text-classification",model='philschmid/BERT-Banking77')

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


In [12]:
while True:
    text = input()
    output = classifier(text)
    print("Predicted output:",output)
    output2=classifier1(text,labels)
    print("pre:",output2)
    if text.lower() == "exit":
            break
# Classify the sentiment
    


My physical card is not working


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-large-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


{'input_ids': tensor([[ 101, 2026, 3558, 4003, 2003, 2025, 2551,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}
tensor([[-3.2110e-01, -5.8184e-01, -4.5155e-01, -2.9002e-01, -1.2346e-01,
         -4.5123e-02, -2.3683e-01, -3.3209e-01,  5.4906e-02, -4.4779e-01,
          1.2798e-01, -1.1887e-01,  4.2947e-01, -4.1594e-01, -9.0766e-01,
         -2.3303e-01, -7.4124e-01, -1.2961e-03, -7.5174e-01,  5.4699e-01,
         -5.6319e-01, -2.2589e-01,  3.8070e-01, -9.2205e-01, -4.2229e-02,
          2.7867e-01, -7.7479e-01, -7.1987e-01,  1.4306e-01,  6.5737e-01,
          2.9739e-01,  2.1060e-01, -1.0367e+00, -3.7862e-01, -1.4094e-01,
         -4.7272e-01, -1.3641e+00, -2.5729e-02,  4.0325e-01,  1.0369e+00,
         -1.8291e-01,  1.3719e-01,  8.3828e-02, -2.1581e-01, -5.5485e-01,
          1.3956e-01,  4.5319e-02, -1.3247e-01, -6.1731e-01,  5.7479e-01,
         -1.8761e-01, -1.5800e-01, -1.4479e-02, -1.0738e+00,  5.0488e-01,
    

Ignoring args : (array([11, 13, 32, 17, 34, 46, 36, 12,  4, 14, 33, 41,  1, 49, 23, 56, 47,
        8, 60, 75, 15, 66, 54, 40, 10, 61,  6, 16, 30, 74, 68, 38, 73, 62,
       29, 22,  3, 28, 44, 26, 45, 42, 52, 27, 51, 25, 48, 55, 18, 63, 70,
       67, 53, 21,  7, 64, 50, 35, 65, 71, 39, 58, 43, 72, 76, 37, 59,  5,
       20, 31, 57,  0, 19,  9,  2, 69, 24], dtype=int64),)


Predicted output: 26
pre: [{'label': 'card_not_working', 'score': 0.9694022536277771}]
exit


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-large-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


{'input_ids': tensor([[ 101, 6164,  102]]), 'token_type_ids': tensor([[0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1]])}
tensor([[-0.8107, -0.0374,  0.0395,  0.0300,  0.0706,  0.0691, -0.6840,  0.6431,
         -0.2955,  0.3342,  0.1211, -0.8487, -0.6035,  0.4615, -0.1597,  0.0761,
         -0.1429, -0.1070,  0.4512, -0.7345,  0.4440, -0.4092, -0.1472,  0.1507,
          0.2428, -0.9915, -0.5736, -0.2929, -0.0506,  0.5300, -0.2767, -0.6839,
          0.2797,  0.6603,  0.8959,  0.3008,  0.4198, -0.5329, -0.5453,  0.2416,
         -0.6002, -0.8692,  1.0410, -0.0572,  0.2593, -1.0521, -0.9508, -0.8959,
          0.9136,  0.9227, -0.0106,  0.6754, -0.3909, -0.0628, -0.3833,  0.2750,
         -0.2144,  0.2833,  0.0673, -0.5535,  0.0250,  0.3396, -0.4446, -1.0846,
          0.7820,  0.7228, -0.4019, -0.3517, -0.2438, -0.1078,  0.4628, -0.0279,
         -0.6756, -0.6901, -0.6912, -0.9729, -0.5241]],
       grad_fn=<AddmmBackward0>)


Ignoring args : (array([11, 13, 32, 17, 34, 46, 36, 12,  4, 14, 33, 41,  1, 49, 23, 56, 47,
        8, 60, 75, 15, 66, 54, 40, 10, 61,  6, 16, 30, 74, 68, 38, 73, 62,
       29, 22,  3, 28, 44, 26, 45, 42, 52, 27, 51, 25, 48, 55, 18, 63, 70,
       67, 53, 21,  7, 64, 50, 35, 65, 71, 39, 58, 43, 72, 76, 37, 59,  5,
       20, 31, 57,  0, 19,  9,  2, 69, 24], dtype=int64),)


Predicted output: 52
pre: [{'label': 'terminate_account', 'score': 0.36598843336105347}]


In [13]:
text = input()
output = classifier(text)
print("Predicted output:",output)
output2=classifier1(text,labels)
print("pre:",output2)

My physical card is not working


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-large-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


{'input_ids': tensor([[ 101, 2026, 3558, 4003, 2003, 2025, 2551,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}


Ignoring args : (array([11, 13, 32, 17, 34, 46, 36, 12,  4, 14, 33, 41,  1, 49, 23, 56, 47,
        8, 60, 75, 15, 66, 54, 40, 10, 61,  6, 16, 30, 74, 68, 38, 73, 62,
       29, 22,  3, 28, 44, 26, 45, 42, 52, 27, 51, 25, 48, 55, 18, 63, 70,
       67, 53, 21,  7, 64, 50, 35, 65, 71, 39, 58, 43, 72, 76, 37, 59,  5,
       20, 31, 57,  0, 19,  9,  2, 69, 24], dtype=int64),)


tensor([[-0.2997,  0.8251, -0.3508, -0.0477, -0.3247,  0.5797,  0.0114,  0.3524,
          0.1216, -0.1002,  0.6737,  0.7951,  0.0487, -0.0994,  0.4256, -0.0263,
          0.3419,  0.7232, -0.1111, -1.2739, -0.0215, -0.1961, -0.6637, -0.3702,
         -0.8544,  0.5752,  0.0453, -0.5544, -0.4626, -1.1888,  0.0869, -0.1233,
          0.1498, -0.1999, -0.0202,  0.2709,  0.1859,  0.3523,  0.0703,  0.0868,
          0.3504, -0.2090,  0.9531,  0.2005,  0.2020,  1.0799,  0.3824,  0.7938,
          0.9139,  0.2063, -0.1609,  0.3809,  0.5537,  0.0058,  0.2563,  0.5713,
          0.2388,  0.1146,  0.2622,  0.4180, -0.2100, -0.7018, -0.0454, -0.8322,
         -0.3643,  0.2078,  0.0729, -0.3843,  0.1776,  0.0125, -1.0106,  0.2984,
         -0.3109,  0.3639, -0.6782, -0.0866, -1.0115]],
       grad_fn=<AddmmBackward0>)
Predicted output: 25
pre: [{'label': 'card_not_working', 'score': 0.9694022536277771}]


In [14]:
hub_llm=HuggingFaceHub(repo_id="gpt2")

In [18]:
prompt=PromptTemplate(
        input_variables=['text'],
        template="The text is {text} and The intent inside the message is {output2} ",
        model_kwargs={'temperature':0.1,'max_length':100}
)

ValidationError: 1 validation error for PromptTemplate
__root__
  Invalid prompt schema; check for mismatched or missing input parameters. 'output2' (type=value_error)

In [16]:
hub_chain=LLMChain(prompt=prompt,llm=hub_llm,verbose=True)

In [17]:
print(hub_chain.run(text))

ValueError: A single string input was passed in, but this chain expects multiple inputs ({'output2', 'text'}). When a chain expects multiple inputs, please call it by passing in a dictionary, eg `chain({'foo': 1, 'bar': 2})`